const state = { id: null, revision: null, events: [], schema: [] };
const $ = (selector) => document.querySelector(selector);
const status = (message, kind = "") => { $("#status").textContent = message; $("#status").className = kind; };
async function request(url, options = {}) { const response = await fetch(url, { ...options, headers: { "content-type": "application/json", ...(options.headers || {}) } }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "请求失败"); return body; }
function renderCharacters(characters) { $("#characters").innerHTML = characters.map((character) => `<button type="button" data-character="${escapeHtml(character.id)}">${escapeHtml(character.name)}<small>${escapeHtml(character.tier)}级</small></button>`).join(""); document.querySelectorAll("[data-character]").forEach((button) => button.addEventListener("click", () => loadDialogue(button.dataset.character))); }
function renderEventOptions() { const existing = new Set(state.events.map((event) => event.code)); const available = state.schema.filter((event) => !existing.has(event.code)); $("#event-code").innerHTML = available.map((event) => `<option value="${escapeHtml(event.code)}">${escapeHtml(event.label)}（${escapeHtml(event.code)}）</option>`).join(""); $("#event-code").disabled = available.length === 0; $("#new-line").disabled = available.length === 0; $("#new-event button").disabled = available.length === 0; }
function renderEvents() { $("#events").innerHTML = state.events.map((event) => `<article class="event" data-event="${event.code}"><header><div><h3>${event.label}</h3><code>${event.code}</code></div><button type="button" data-delete="${event.code}">删除对白组</button></header><div class="lines">${event.lines.map((line) => `<div class="line"><textarea>${escapeHtml(line)}</textarea><button type="button" data-remove-line>删除行</button></div>`).join("")}</div><button type="button" data-add-line>增加一行</button><button type="button" class="save" data-save="${event.code}">保存本组</button></article>`).join(""); document.querySelectorAll("[data-add-line]").forEach((button) => button.addEventListener("click", () => { const line = document.createElement("div"); line.className = "line"; line.innerHTML = '<textarea></textarea><button type="button" data-remove-line>删除行</button>'; line.querySelector("[data-remove-line]").addEventListener("click", () => line.remove()); button.previousElementSibling.append(line); })); document.querySelectorAll("[data-remove-line]").forEach((button) => button.addEventListener("click", () => button.parentElement.remove())); document.querySelectorAll("[data-save]").forEach((button) => button.addEventListener("click", () => saveEvent(button.dataset.save))); document.querySelectorAll("[data-delete]").forEach((button) => button.addEventListener("click", () => deleteEvent(button.dataset.delete))); }
function escapeHtml(value) { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character])); }
async function loadDialogue(id) { try { const body = await request(`/api/characters/${encodeURIComponent(id)}/dialogue`, { headers: {} }); state.id = id; state.revision = body.revision; state.events = body.events; state.schema = body.schema || state.schema; $("#character-name").textContent = body.name; $("#revision").textContent = body.revision; $("#empty").hidden = true; $("#dialogue").hidden = false; renderEvents(); renderEventOptions(); status("已加载。"); document.querySelectorAll("[data-character]").forEach((button) => button.classList.toggle("selected", button.dataset.character === id)); } catch (error) { status(error.message, "error"); } }
function updateRevision(body) { state.revision = body.revision; state.events = body.events; $("#revision").textContent = body.revision; renderEvents(); renderEventOptions(); }
async function saveEvent(code) { try { const article = document.querySelector(`[data-event="${code}"]`); const lines = [...article.querySelectorAll("textarea")].map((textarea) => textarea.value); const body = await request(`/api/characters/${encodeURIComponent(state.id)}/dialogue/${code}`, { method: "PUT", headers: { "if-match": state.revision }, body: JSON.stringify({ lines }) }); updateRevision(body); status("本组对白已保存。", "ok"); } catch (error) { status(error.message, "error"); } }
async function deleteEvent(code) { if (!confirm(`确定删除 ${code} 对白组吗？`)) return; try { const body = await request(`/api/characters/${encodeURIComponent(state.id)}/dialogue/${code}`, { method: "DELETE", headers: { "if-match": state.revision } }); updateRevision(body); status("对白组已删除。", "ok"); } catch (error) { status(error.message, "error"); } }
$("#new-event").addEventListener("submit", async (event) => { event.preventDefault(); const code = $("#event-code").value; const firstLine = $("#new-line").value; try { const body = await request(`/api/characters/${encodeURIComponent(state.id)}/dialogue`, { method: "POST", headers: { "if-match": state.revision }, body: JSON.stringify({ event: code, lines: [firstLine] }) }); updateRevision(body); $("#new-line").value = ""; status("对白组已创建。", "ok"); } catch (error) { status(error.message, "error"); } });
$("#reload").addEventListener("click", () => loadDialogue(state.id));
request("/api/characters").then((body) => { state.schema = body.events; renderCharacters(body.characters); }).catch((error) => status(error.message, "error"));
